[profile.default]
src = 'src'
test = 'src/test'
test_match = '*.t.sol'
no_match_path = 'src/LibTest.sol'
allow_paths = ['../']
evm_version = 'cancun'
solc = '0.8.28'
optimizer = true

[lint]
lint_on_build = false